#!/bin/bash
# DEPRECATED: 'msam' is the previous name of this script. Use 'saga' going forward.
# This shim will be removed in a future release. It forwards to the saga-named binary.
exec "$(dirname "$0")/saga" "$@"
