"""CommitmentsStore — append-only lifecycle + replay + status-aware trim."""

from __future__ import annotations

import json
import time
from pathlib import Path

import pytest

from mimir.commitments import (
    CommitmentKind,
    CommitmentRecord,
    CommitmentSensitivity,
    CommitmentStatus,
    CommitmentsStore,
    make_commitment_id,
    make_dedupe_key,
)


# ─── make_dedupe_key ────────────────────────────────────────────────


def test_dedupe_key_stable_for_same_inputs():
    k1 = make_dedupe_key(channel_id="c1", text="Review PR", due_window_start_unix=None)
    k2 = make_dedupe_key(channel_id="c1", text="Review PR", due_window_start_unix=None)
    assert k1 == k2


def test_dedupe_key_normalizes_whitespace_and_case():
    k1 = make_dedupe_key(channel_id="c1", text="Review PR", due_window_start_unix=None)
    k2 = make_dedupe_key(channel_id="c1", text="  REVIEW   pr  ", due_window_start_unix=None)
    assert k1 == k2


def test_dedupe_key_distinguishes_channels():
    k1 = make_dedupe_key(channel_id="c1", text="Review PR", due_window_start_unix=None)
    k2 = make_dedupe_key(channel_id="c2", text="Review PR", due_window_start_unix=None)
    assert k1 != k2


def test_dedupe_key_buckets_by_day_not_second():
    """Same due day → same key. Different days → different keys."""
    base = 1_715_000_000.0  # arbitrary unix
    k1 = make_dedupe_key(channel_id="c1", text="X", due_window_start_unix=base)
    k2 = make_dedupe_key(channel_id="c1", text="X", due_window_start_unix=base + 3600)
    k3 = make_dedupe_key(channel_id="c1", text="X", due_window_start_unix=base + 86400 * 2)
    assert k1 == k2  # same day
    assert k1 != k3  # different day


def test_dedupe_key_none_due_bucket_is_consistent():
    k1 = make_dedupe_key(channel_id="c1", text="X", due_window_start_unix=None)
    k2 = make_dedupe_key(channel_id="c1", text="X", due_window_start_unix=None)
    assert k1 == k2


def test_dedupe_key_distinguishes_recipients():
    """Same channel + same text but different recipients are distinct
    commitments — without this, "remind Alice about X" and "remind Bob
    about X" in the same channel would dedupe together and the second
    would lose its addressee on extraction."""
    k_alice = make_dedupe_key(
        channel_id="c1", text="X", due_window_start_unix=None,
        recipient_identity="alice",
    )
    k_bob = make_dedupe_key(
        channel_id="c1", text="X", due_window_start_unix=None,
        recipient_identity="bob",
    )
    k_none = make_dedupe_key(
        channel_id="c1", text="X", due_window_start_unix=None,
    )
    assert k_alice != k_bob
    assert k_alice != k_none
    assert k_bob != k_none


# ─── Basic add + replay ─────────────────────────────────────────────


@pytest.mark.asyncio
async def test_add_and_replay_round_trips(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "commitments.jsonl")
    rec = CommitmentRecord(
        id=make_commitment_id(),
        channel_id="chan-1",
        text="Review PR #111",
        kind=CommitmentKind.AGENT_PROMISE.value,
        suggested_reminder="PR #111 awaiting review",
    )
    saved = await store.add(rec)

    state = store.current_state()
    assert saved.id in state
    out = state[saved.id]
    assert out.text == "Review PR #111"
    assert out.status == CommitmentStatus.PENDING.value
    assert out.kind == CommitmentKind.AGENT_PROMISE.value
    assert out.dedupe_key  # auto-filled
    assert out.created_at_unix > 0  # auto-filled


@pytest.mark.asyncio
async def test_add_persists_recipient_identity(tmp_path: Path):
    """The recipient field round-trips through JSONL → replay."""
    store = CommitmentsStore(path=tmp_path / "commitments.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(),
        channel_id="chan-1",
        text="Remind Alice about deploy outcome",
        kind=CommitmentKind.USER_REQUEST.value,
        recipient_identity="alice",
    ))
    state = store.current_state()
    assert state[rec.id].recipient_identity == "alice"


@pytest.mark.asyncio
async def test_add_autogenerated_dedupe_key_includes_recipient(tmp_path: Path):
    """Same channel + same text + different recipients → different
    auto-generated dedupe keys (so neither suppresses the other on
    extraction)."""
    store = CommitmentsStore(path=tmp_path / "commitments.jsonl")
    r1 = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        recipient_identity="alice",
    ))
    r2 = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        recipient_identity="bob",
    ))
    assert r1.dedupe_key != r2.dedupe_key


@pytest.mark.asyncio
async def test_add_coerces_initial_status_to_pending(tmp_path: Path):
    """A caller copy-pasting status=completed on add() must NOT poison
    the store — the contract is that add() starts pending."""
    store = CommitmentsStore(path=tmp_path / "commitments.jsonl")
    rec = CommitmentRecord(
        id=make_commitment_id(),
        channel_id="chan-1",
        text="X",
        status=CommitmentStatus.COMPLETED.value,  # wrong; should be coerced
    )
    saved = await store.add(rec)
    assert saved.status == CommitmentStatus.PENDING.value
    state = store.current_state()
    assert state[saved.id].status == CommitmentStatus.PENDING.value


# ─── Lifecycle transitions ───────────────────────────────────────────


@pytest.mark.asyncio
async def test_deliver_bumps_attempts_and_sets_status(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.deliver(rec.id)
    await store.deliver(rec.id)

    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.DELIVERED.value
    assert state[rec.id].attempts == 2


@pytest.mark.asyncio
async def test_complete_is_terminal(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.complete(rec.id, message_id="m-42")

    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.COMPLETED.value
    assert state[rec.id].completion_message_id == "m-42"
    assert state[rec.id].is_terminal()


@pytest.mark.asyncio
async def test_snooze_slides_due_window_start(tmp_path: Path):
    """Snoozing should push the due_window_start so surfacing logic
    knows the next earliest-deliver anchor."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    original_start = 1_000_000.0
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        due_window_start_unix=original_start,
        due_window_end_unix=original_start + 86400,
    ))
    new_start = original_start + 7 * 86400
    await store.snooze(rec.id, until_unix=new_start, reason="not yet")

    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.SNOOZED.value
    assert state[rec.id].snoozed_until_unix == new_start
    assert state[rec.id].due_window_start_unix == new_start
    assert state[rec.id].snooze_reason == "not yet"


@pytest.mark.asyncio
async def test_dismiss_with_reason(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.dismiss(rec.id, reason="no longer relevant")

    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.DISMISSED.value
    assert state[rec.id].dismiss_reason == "no longer relevant"
    assert state[rec.id].is_terminal()


@pytest.mark.asyncio
async def test_expire(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.expire(rec.id)

    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.EXPIRED.value
    assert state[rec.id].is_terminal()


@pytest.mark.asyncio
async def test_lifecycle_event_for_unknown_id_is_skipped(tmp_path: Path):
    """Replay must tolerate lifecycle events whose add was trimmed
    away — log + skip, not crash."""
    path = tmp_path / "c.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    # Write a delivered event without a preceding add.
    with path.open("w") as f:
        f.write(json.dumps({
            "type": "commitment_delivered",
            "id": "c-orphan",
            "at_unix": time.time(),
        }) + "\n")
    store = CommitmentsStore(path=path)
    state = store.current_state()
    assert state == {}  # nothing created, no crash


# ─── List filters ────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_list_filters_by_channel(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    await store.add(CommitmentRecord(id=make_commitment_id(), channel_id="ch1", text="X1"))
    await store.add(CommitmentRecord(id=make_commitment_id(), channel_id="ch2", text="X2"))
    await store.add(CommitmentRecord(id=make_commitment_id(), channel_id=None, text="X3-unbound"))

    rows_ch1 = store.list(channel_id="ch1")
    # ch1-bound + unbound (per design rule "unbound surfaces everywhere")
    assert {r.text for r in rows_ch1} == {"X1", "X3-unbound"}

    rows_ch1_strict = store.list(channel_id="ch1", include_unbound=False)
    assert {r.text for r in rows_ch1_strict} == {"X1"}


@pytest.mark.asyncio
async def test_list_filters_by_status(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    r1 = await store.add(CommitmentRecord(id=make_commitment_id(), channel_id="c1", text="X1"))
    r2 = await store.add(CommitmentRecord(id=make_commitment_id(), channel_id="c1", text="X2"))
    await store.complete(r1.id)

    pending = store.list(status=CommitmentStatus.PENDING.value)
    completed = store.list(status=CommitmentStatus.COMPLETED.value)
    assert {r.text for r in pending} == {"X2"}
    assert {r.text for r in completed} == {"X1"}


@pytest.mark.asyncio
async def test_list_sorted_by_created_at(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    base = time.time()
    r1 = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="first",
        created_at_unix=base,
    ))
    r2 = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="second",
        created_at_unix=base + 100,
    ))
    r3 = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="third",
        created_at_unix=base + 50,
    ))
    rows = store.list()
    assert [r.text for r in rows] == ["first", "third", "second"]


# ─── find_by_dedupe_key ──────────────────────────────────────────────


@pytest.mark.asyncio
async def test_find_by_dedupe_key_returns_active(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="Review PR #1",
    ))
    found = store.find_by_dedupe_key(rec.dedupe_key)
    assert found is not None
    assert found.id == rec.id


@pytest.mark.asyncio
async def test_find_by_dedupe_key_ignores_terminal(tmp_path: Path):
    """A completed/dismissed commitment shouldn't dedupe a fresh extraction
    — the new one is a re-emergence, treat as new."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="Review PR #1",
    ))
    await store.complete(rec.id)
    assert store.find_by_dedupe_key(rec.dedupe_key) is None


# ─── Status-aware trim ──────────────────────────────────────────────


@pytest.mark.asyncio
async def test_trim_drops_terminal_records_older_than_retention(tmp_path: Path):
    store = CommitmentsStore(
        path=tmp_path / "c.jsonl",
        terminal_retention_days=30,
    )
    now = time.time()
    # Old completed record (40 days ago) — should drop.
    r_old = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="old",
        created_at_unix=now - 40 * 86400,
    ))
    await store.complete(r_old.id)
    # Hand-rewrite to backdate the completed event so trim sees it as
    # old. (The store writes its own at_unix=time.time(); to test trim
    # we need to manipulate the event after the fact.)
    path = tmp_path / "c.jsonl"
    new_lines = []
    for line in path.read_text().splitlines():
        d = json.loads(line)
        if d.get("type") == "commitment_completed" and d.get("id") == r_old.id:
            d["at_unix"] = now - 40 * 86400
        new_lines.append(json.dumps(d))
    path.write_text("\n".join(new_lines) + "\n")

    # Recent completed record (1 day ago) — should keep.
    r_recent = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="recent",
    ))
    await store.complete(r_recent.id)

    dropped = await store.trim(now_unix=now)
    assert dropped == 1
    state = store.current_state()
    assert r_old.id not in state
    assert r_recent.id in state


@pytest.mark.asyncio
async def test_trim_never_drops_pending_no_matter_how_old(tmp_path: Path):
    """A 60-day pending commitment survives every trim."""
    store = CommitmentsStore(
        path=tmp_path / "c.jsonl",
        terminal_retention_days=30,
    )
    now = time.time()
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="long-deadline",
        created_at_unix=now - 60 * 86400,
        due_window_start_unix=now + 30 * 86400,
    ))
    dropped = await store.trim(now_unix=now)
    assert dropped == 0
    assert rec.id in store.current_state()


@pytest.mark.asyncio
async def test_trim_never_drops_snoozed_indefinitely(tmp_path: Path):
    """Snoozed-far-into-future is still active; trim must leave it."""
    store = CommitmentsStore(
        path=tmp_path / "c.jsonl",
        terminal_retention_days=30,
    )
    now = time.time()
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="snoozed-out",
    ))
    await store.snooze(rec.id, until_unix=now + 365 * 86400)
    dropped = await store.trim(now_unix=now)
    assert dropped == 0
    assert rec.id in store.current_state()


@pytest.mark.asyncio
async def test_trim_empty_file_returns_zero(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    assert await store.trim() == 0


# ─── Path / file behavior ────────────────────────────────────────────


@pytest.mark.asyncio
async def test_missing_file_yields_empty_state(tmp_path: Path):
    """Replay on a never-written file is fine — returns empty dict."""
    store = CommitmentsStore(path=tmp_path / "nonexistent.jsonl")
    assert store.current_state() == {}
    assert store.list() == []


@pytest.mark.asyncio
async def test_add_creates_parent_directory(tmp_path: Path):
    """Store path can include intermediate dirs that don't exist yet."""
    store = CommitmentsStore(path=tmp_path / ".mimir" / "subdir" / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    assert store.path.is_file()
    assert rec.id in store.current_state()


@pytest.mark.asyncio
async def test_jsonl_format_is_one_event_per_line(tmp_path: Path):
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    r1 = await store.add(CommitmentRecord(id=make_commitment_id(), channel_id="c1", text="X1"))
    await store.deliver(r1.id)
    await store.complete(r1.id)

    lines = store.path.read_text().splitlines()
    assert len(lines) == 3
    for line in lines:
        json.loads(line)  # each line is valid JSON


# ─── PR #120 review fixes: lifecycle guards ─────────────────────────


@pytest.mark.asyncio
async def test_replay_rejects_transitions_from_terminal_state(tmp_path: Path):
    """PR #120 review #1: a lifecycle event arriving for a record
    already in a terminal state (completed/dismissed/expired) must NOT
    silently flip the status. The VALID_TRANSITIONS adjacency rejects
    it; the original terminal state stands."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.complete(rec.id, message_id="m-1")
    # Late-arriving expire (the Phase 2 expire-poller scenario).
    await store.expire(rec.id)

    state = store.current_state()
    # Still completed; expire was rejected.
    assert state[rec.id].status == CommitmentStatus.COMPLETED.value
    assert state[rec.id].completion_message_id == "m-1"
    assert state[rec.id].expired_at_unix is None


@pytest.mark.asyncio
async def test_replay_rejects_dismiss_after_complete(tmp_path: Path):
    """Same shape — once completed, any further transition is rejected."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.complete(rec.id)
    await store.dismiss(rec.id, reason="too late")
    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.COMPLETED.value
    assert state[rec.id].dismiss_reason is None


@pytest.mark.asyncio
async def test_replay_allows_redelivery(tmp_path: Path):
    """Self-transition DELIVERED → DELIVERED is allowed (attempt bump
    on each delivery). The guard rejects only non-listed transitions."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.deliver(rec.id)
    await store.deliver(rec.id)
    await store.deliver(rec.id)
    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.DELIVERED.value
    assert state[rec.id].attempts == 3


@pytest.mark.asyncio
async def test_replay_allows_resnooze(tmp_path: Path):
    """SNOOZED → SNOOZED is allowed; pushing out further."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.snooze(rec.id, until_unix=time.time() + 86400)
    await store.snooze(rec.id, until_unix=time.time() + 7 * 86400)
    state = store.current_state()
    assert state[rec.id].status == CommitmentStatus.SNOOZED.value


@pytest.mark.asyncio
async def test_replay_duplicate_add_keeps_first(tmp_path: Path):
    """PR #120 review #2: a second commitment_added for the same id
    must NOT overwrite in-progress state. The replay keeps the first
    add + accumulated lifecycle progress; the duplicate is a no-op."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    cid = make_commitment_id()
    rec = await store.add(CommitmentRecord(
        id=cid, channel_id="c1", text="original",
    ))
    await store.deliver(rec.id)
    await store.deliver(rec.id)
    # Caller-bug: adds the same id again with different text.
    duplicate = CommitmentRecord(id=cid, channel_id="c1", text="DUPLICATE")
    await store.add(duplicate)

    state = store.current_state()
    # Original text preserved; lifecycle progress (attempts=2) intact.
    assert state[cid].text == "original"
    assert state[cid].status == CommitmentStatus.DELIVERED.value
    assert state[cid].attempts == 2


# ─── Snooze due-window bumping (review #3) ───────────────────────────


@pytest.mark.asyncio
async def test_snooze_bumps_end_when_start_exceeds_it(tmp_path: Path):
    """PR #120 review #3: a snooze that pushes ``start`` past the
    existing ``end`` must bump ``end`` so the window stays positive.
    Without this guard, downstream surfacing would see start > end
    and have to defensively reject."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    start = time.time()
    end = start + 86400  # 1-day window
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        due_window_start_unix=start,
        due_window_end_unix=end,
    ))
    # Snooze 30 days out — well past the original 1-day end.
    new_start = start + 30 * 86400
    await store.snooze(rec.id, until_unix=new_start)
    state = store.current_state()
    assert state[rec.id].due_window_start_unix == new_start
    # End bumped to new_start + 7 days (DEFAULT_SNOOZE_WINDOW_SECS).
    assert state[rec.id].due_window_end_unix == new_start + 7 * 86400


@pytest.mark.asyncio
async def test_snooze_preserves_longer_existing_end(tmp_path: Path):
    """If the existing end is already further out than start + default
    window, leave it alone — don't shorten the window."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    start = time.time()
    end = start + 365 * 86400  # 1-year window
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        due_window_start_unix=start,
        due_window_end_unix=end,
    ))
    new_start = start + 30 * 86400
    await store.snooze(rec.id, until_unix=new_start)
    state = store.current_state()
    # End untouched (still the original 1-year mark, which is further
    # out than new_start + 7 days).
    assert state[rec.id].due_window_end_unix == end


@pytest.mark.asyncio
async def test_snooze_sets_end_when_none(tmp_path: Path):
    """If the original record had no end (open-ended), snooze sets one
    so the post-snooze record is well-formed."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
        # No due_window_start_unix / due_window_end_unix.
    ))
    new_start = time.time() + 86400
    await store.snooze(rec.id, until_unix=new_start)
    state = store.current_state()
    assert state[rec.id].due_window_start_unix == new_start
    assert state[rec.id].due_window_end_unix == new_start + 7 * 86400


# ─── Trim fsync (review #4a) ────────────────────────────────────────


@pytest.mark.asyncio
async def test_trim_fsyncs_before_replace(tmp_path: Path, monkeypatch):
    """PR #120 review #4a: trim must flush + fsync the tmp file before
    os.replace, so the durability claim ("interrupted trim never
    leaves the store half-written") actually holds. Monkeypatch
    os.fsync to verify it's called on the tmp file's fd."""
    import os as _os
    fsynced_fds: list[int] = []
    original_fsync = _os.fsync

    def tracking_fsync(fd: int) -> None:
        fsynced_fds.append(fd)
        original_fsync(fd)

    monkeypatch.setattr(_os, "fsync", tracking_fsync)

    store = CommitmentsStore(
        path=tmp_path / "c.jsonl",
        terminal_retention_days=30,
    )
    now = time.time()
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    await store.complete(rec.id)
    # Backdate so trim picks it up.
    path = tmp_path / "c.jsonl"
    lines = []
    for line in path.read_text().splitlines():
        d = json.loads(line)
        if d.get("type") == "commitment_completed":
            d["at_unix"] = now - 40 * 86400
        lines.append(json.dumps(d))
    path.write_text("\n".join(lines) + "\n")

    dropped = await store.trim(now_unix=now)
    assert dropped == 1
    # fsync was called at least once during the trim's write path.
    assert len(fsynced_fds) >= 1


# ─── PR #120 re-review N1 + N2 ───────────────────────────────────────


@pytest.mark.asyncio
async def test_write_methods_return_false_on_terminal_rejection(tmp_path: Path):
    """PR #120 re-review N2: write-path methods now return bool. A
    write against an already-terminal record returns False AND skips
    the JSONL append, instead of appending a no-op event that replay
    would silently reject. Saves JSONL bloat + gives the CLI a signal
    to surface to the operator."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    assert await store.complete(rec.id) is True
    # Now-terminal record rejects further transitions at the write path.
    assert await store.complete(rec.id) is False
    assert await store.dismiss(rec.id) is False
    assert await store.expire(rec.id) is False
    assert await store.snooze(rec.id, until_unix=time.time() + 86400) is False
    assert await store.deliver(rec.id) is False
    # JSONL only has the original add + complete — no no-op events.
    lines = store.path.read_text().splitlines()
    assert len(lines) == 2
    assert json.loads(lines[0])["type"] == "commitment_added"
    assert json.loads(lines[1])["type"] == "commitment_completed"


@pytest.mark.asyncio
async def test_write_methods_return_false_on_unknown_id(tmp_path: Path):
    """Unknown id → False on every lifecycle method, no events appended."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    assert await store.complete("c-nonexistent") is False
    assert await store.dismiss("c-nonexistent") is False
    assert await store.expire("c-nonexistent") is False
    assert await store.deliver("c-nonexistent") is False
    assert await store.snooze("c-nonexistent", until_unix=time.time()) is False
    # No file created (no appends happened).
    assert not store.path.exists()


@pytest.mark.asyncio
async def test_write_methods_return_true_on_valid_transitions(tmp_path: Path):
    """Sanity: the bool return is True for legitimate transitions."""
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="X",
    ))
    assert await store.deliver(rec.id) is True
    assert await store.deliver(rec.id) is True  # re-deliver allowed
    assert await store.snooze(rec.id, until_unix=time.time() + 86400) is True
    assert await store.complete(rec.id) is True


@pytest.mark.asyncio
async def test_find_trim_candidates_shares_predicate_with_trim(tmp_path: Path):
    """PR #120 re-review N1: ``find_trim_candidates`` is the single
    source of truth for the trim predicate; trim() uses it for the
    drop set, the CLI dry-run uses it for the preview. Same input
    must yield the same output, by construction."""
    store = CommitmentsStore(
        path=tmp_path / "c.jsonl",
        terminal_retention_days=30,
    )
    now = time.time()
    # Two terminals: one old (should be a candidate), one fresh (not).
    r_old = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="old",
    ))
    await store.complete(r_old.id)
    r_fresh = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="fresh",
    ))
    await store.complete(r_fresh.id)
    # Plus one active that should never be a candidate.
    r_active = await store.add(CommitmentRecord(
        id=make_commitment_id(), channel_id="c1", text="active",
    ))
    # Backdate r_old's terminal event.
    new_lines = []
    for line in store.path.read_text().splitlines():
        d = json.loads(line)
        if d.get("type") == "commitment_completed" and d.get("id") == r_old.id:
            d["at_unix"] = now - 40 * 86400
        new_lines.append(json.dumps(d))
    store.path.write_text("\n".join(new_lines) + "\n")

    candidates = store.find_trim_candidates(now_unix=now)
    candidate_ids = {rid for rid, _ in candidates}
    assert candidate_ids == {r_old.id}
    assert r_fresh.id not in candidate_ids  # too recent
    assert r_active.id not in candidate_ids  # not terminal

    # trim() with the same inputs drops the same set.
    dropped = await store.trim(now_unix=now)
    assert dropped == 1
    state = store.current_state()
    assert r_old.id not in state
    assert r_fresh.id in state
    assert r_active.id in state


def test_find_trim_candidates_returns_record_objects(tmp_path: Path):
    """``find_trim_candidates`` returns ``list[tuple[str, CommitmentRecord]]``
    so the CLI dry-run can print rich per-record info without a second
    lookup."""
    import asyncio
    store = CommitmentsStore(path=tmp_path / "c.jsonl")

    async def setup():
        rec = await store.add(CommitmentRecord(
            id=make_commitment_id(), channel_id="c1",
            text="payload", kind=CommitmentKind.AGENT_PROMISE.value,
        ))
        await store.complete(rec.id)
        # Backdate.
        now = time.time()
        new_lines = []
        for line in store.path.read_text().splitlines():
            d = json.loads(line)
            if d.get("type") == "commitment_completed":
                d["at_unix"] = now - 40 * 86400
            new_lines.append(json.dumps(d))
        store.path.write_text("\n".join(new_lines) + "\n")
        return rec.id

    rid = asyncio.run(setup())
    out = store.find_trim_candidates()
    assert len(out) == 1
    cid, rec = out[0]
    assert cid == rid
    assert rec.text == "payload"
    assert rec.kind == CommitmentKind.AGENT_PROMISE.value


# ─── chainlink #82 sub #86: JSONL schema version envelope ───────────


@pytest.mark.asyncio
async def test_append_stamps_schema_version_on_every_event(tmp_path: Path):
    """Every event written through ``_append`` carries the current
    schema version under the ``v`` key — covers add + every lifecycle
    method (delivered, completed, snoozed, dismissed, expired,
    pileup_alarmed). Chainlink #82 sub #86."""
    from mimir.commitments.store import COMMITMENTS_JSONL_SCHEMA_VERSION
    store = CommitmentsStore(path=tmp_path / "c.jsonl")
    rec = await store.add(CommitmentRecord(
        id=make_commitment_id(),
        channel_id="c1", text="t",
        kind=CommitmentKind.AGENT_PROMISE.value,
    ))
    await store.deliver(rec.id)
    await store.snooze(rec.id, until_unix=time.time() + 60)
    await store.complete(rec.id)
    await store.alarm_pileup(rec.id)
    lines = store.path.read_text().splitlines()
    assert len(lines) >= 4
    for line in lines:
        event = json.loads(line)
        assert event.get("v") == COMMITMENTS_JSONL_SCHEMA_VERSION, (
            f"missing/wrong v on event {event!r}"
        )


@pytest.mark.asyncio
async def test_replay_treats_missing_v_as_current_version(tmp_path: Path):
    """Legacy events (appended before chainlink #82 sub #86 landed)
    have no ``v`` key. Replay must treat them as the current schema —
    that's the backward-compat guarantee."""
    path = tmp_path / "c.jsonl"
    rid = make_commitment_id()
    rec_data = {
        "id": rid,
        "channel_id": "c1",
        "text": "legacy",
        "kind": CommitmentKind.AGENT_PROMISE.value,
        "status": CommitmentStatus.PENDING.value,
        "created_at_unix": time.time(),
        "dedupe_key": make_dedupe_key(
            channel_id="c1", text="legacy", due_window_start_unix=None,
        ),
    }
    # Legacy: no v field
    legacy_event = {
        "type": "commitment_added",
        "ts_unix": time.time(),
        "id": rid,
        "record": rec_data,
    }
    path.write_text(json.dumps(legacy_event) + "\n")
    store = CommitmentsStore(path=path)
    state = store.current_state()
    assert rid in state
    assert state[rid].text == "legacy"


@pytest.mark.asyncio
async def test_replay_skips_future_schema_version(tmp_path: Path, caplog):
    """Events stamped with v greater than this build's schema version
    are skipped on replay (the new event might rely on fields this
    build doesn't know about — replaying as-is risks corrupt state).
    A warning is logged so the operator sees the version skew."""
    import logging
    from mimir.commitments.store import COMMITMENTS_JSONL_SCHEMA_VERSION
    path = tmp_path / "c.jsonl"
    rid = make_commitment_id()
    future_event = {
        "v": COMMITMENTS_JSONL_SCHEMA_VERSION + 1,
        "type": "commitment_added",
        "ts_unix": time.time(),
        "id": rid,
        "record": {
            "id": rid, "channel_id": "c1", "text": "from-future",
            "kind": CommitmentKind.AGENT_PROMISE.value,
            "status": CommitmentStatus.PENDING.value,
            "created_at_unix": time.time(),
        },
    }
    path.write_text(json.dumps(future_event) + "\n")
    store = CommitmentsStore(path=path)
    with caplog.at_level(logging.WARNING, logger="mimir.commitments.store"):
        state = store.current_state()
    assert rid not in state  # future event dropped
    assert any(
        "future schema" in r.getMessage()
        for r in caplog.records
    )


@pytest.mark.asyncio
async def test_replay_skips_malformed_v(tmp_path: Path, caplog):
    """A ``v`` field that isn't parseable as int (e.g. dict, list,
    non-numeric string) gets skipped with a warning. Defensive against
    a corrupt write."""
    import logging
    path = tmp_path / "c.jsonl"
    rid = make_commitment_id()
    bad_v_event = {
        "v": {"unexpected": "shape"},
        "type": "commitment_added",
        "ts_unix": time.time(),
        "id": rid,
        "record": {
            "id": rid, "channel_id": "c1", "text": "bad-v",
            "kind": CommitmentKind.AGENT_PROMISE.value,
            "status": CommitmentStatus.PENDING.value,
            "created_at_unix": time.time(),
        },
    }
    path.write_text(json.dumps(bad_v_event) + "\n")
    store = CommitmentsStore(path=path)
    with caplog.at_level(logging.WARNING, logger="mimir.commitments.store"):
        state = store.current_state()
    assert rid not in state
    assert any(
        "malformed v" in r.getMessage()
        for r in caplog.records
    )
